FROM maven:3-eclipse-temurin-17-alpine as build
WORKDIR /app
COPY pom.xml .
COPY src ./src 
RUN mvn clean package 

FROM eclipse-temurin:17.0.8.1_1-jdk-focal 
WORKDIR /app
COPY --from=build /app/target/GenerativeSkillsFactory-0.0.1-SNAPSHOT.jar  ./GenerativeSkillsFactory.jar
EXPOSE 8081
ENTRYPOINT [ "java","-jar","GenerativeSkillsFactory.jar" ]
